### PR TITLE
fix Error parsing filter using ghost@3.x

### LINKED ISSUE #5: Error parsing filter on every request
Might be related to this https://forum.ghost.org/t/problem-with-filter-by-tags/13262

```
[2020-11-21 12:05:33] ERROR Error parsing filter

Error parsing filter

Error ID:
    db82fec0-2bf1-11eb-9df8-5f80a57020bd

----------------------------------------

BadRequestError: Error parsing filter
    at new BadRequestError (/var/lib/ghost/versions/3.38.2/node_modules/ghost-ignition/lib/errors/index.js:113:23)
    at Child.applyDefaultAndCustomFilters (/var/lib/ghost/versions/3.38.2/core/server/models/plugins/filter.js:122:23)
    at Function.getFilteredCollection (/var/lib/ghost/versions/3.38.2/core/server/models/base/index.js:850:28)
    at Function.findPage (/var/lib/ghost/versions/3.38.2/core/server/models/base/index.js:926:37)
    at Object.query (/var/lib/ghost/versions/3.38.2/core/server/api/canary/posts-public.js:33:32)
    at Object.query (/var/lib/ghost/versions/3.38.2/core/server/api/shared/pipeline.js:156:24)
    at /var/lib/ghost/versions/3.38.2/core/server/api/shared/pipeline.js:243:35
    at tryCatcher (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:15:14)

Error: Query Error: unexpected character in filter at char 7
(tags:[]+id:-)+type:post
-------^
Expecting 'NULL', 'TRUE', 'FALSE', 'NUMBER', 'LITERAL', 'STRING', got 'RBRACKET'
    at Parser.parser.parseError (/var/lib/ghost/versions/3.38.2/node_modules/@nexes/nql-lang/dist/parser.js:328:12)
    at Parser.parse (/var/lib/ghost/versions/3.38.2/node_modules/@nexes/nql-lang/dist/parser.js:245:22)
    at Object.exports.parse (/var/lib/ghost/versions/3.38.2/node_modules/@nexes/nql-lang/lib/nql.js:18:44)
    at Object.api.parse (/var/lib/ghost/versions/3.38.2/node_modules/@nexes/nql/lib/nql.js:15:31)
    at Object.api.querySQL (/var/lib/ghost/versions/3.38.2/node_modules/@nexes/nql/lib/nql.js:49:44)
    at Builder.<anonymous> (/var/lib/ghost/versions/3.38.2/core/server/models/plugins/filter.js:119:24)
    at Object.query (/var/lib/ghost/versions/3.38.2/node_modules/bookshelf/lib/helpers.js:57:14)
    at Child.query (/var/lib/ghost/versions/3.38.2/node_modules/bookshelf/lib/model.js:1256:22)
    at Child.applyDefaultAndCustomFilters (/var/lib/ghost/versions/3.38.2/core/server/models/plugins/filter.js:112:22)
    at Function.getFilteredCollection (/var/lib/ghost/versions/3.38.2/core/server/models/base/index.js:850:28)
    at Function.findPage (/var/lib/ghost/versions/3.38.2/core/server/models/base/index.js:926:37)
    at Object.query (/var/lib/ghost/versions/3.38.2/core/server/api/canary/posts-public.js:33:32)
    at Object.query (/var/lib/ghost/versions/3.38.2/core/server/api/shared/pipeline.js:156:24)
    at /var/lib/ghost/versions/3.38.2/core/server/api/shared/pipeline.js:243:35
    at tryCatcher (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:547:31)
```

### PR DESCRIPTION
**Pull request by Ewocker**
fix #5

### CODE REVIEW

**Comment by minimaluminium** [comment]
Hey Ewing, thanks for your PR! Before going further with this, I'm trying to reproduce the issue on my end with no luck. Could you post the tags of the post you had the issue with?

**Comment by Ewocker** [comment]
I basically set it up with docker compose using the official image, and I remember seeing that even with the initial "Getting start" tag. Let me know if you cannot reproduce that on your side, I can set up a repo for that. The versions I saw the issue are 3.38.2 and 3.38.3 (basically ghost:3-alpine image), and I have not tried any previous version yet.

BTW, just joined that community couple days ago and love ghost and the Ruby theme!

**Comment by minimaluminium** [comment]
Sorry about the delay. Just tested it on a fresh Ghost instance `3.39.0` and couldn't reproduce the issue as well. [Here](https://www.dropbox.com/s/gndt31l7paf41j1/Ruby%20Related%20Posts%20Test.mov?dl=0) is a screencast I've made.

> just joined that community couple days ago and love ghost and the Ruby theme!

Really glad to hear that 🙂

**Comment by minimaluminium** [comment]
Could't reproduce the issue, and closing due to inactivity.

**Pull request closed without merging**
